### ISSUE TITLE
[Request] Add better documentation

### ISSUE THREAD

**Issue by Rycia** [Drahsid/ResizableHUD#4]
I will say, I really want to use this plugin; but I have one, very big issue with it.

When you open the plugin using `/prhud`, by default, nothing is added and has to be found through `/xldata`.
Problem is, when you open `/xldata`, you're not told (or can find) where the data is that you're looking for, and no documentation is out there through a quick google search as to what these elements are or where to find them.

In my case, I wanted to find the element for my hotbars, chat, and separate out my HP and MP gauges.
I was able to find `_HotbarX` (where x is 1 through 9) only by seeing it existed looking at other issues and checking if anyone else complained about this.

And once I added `/prhudadd _Hotbar1` and changed the value of positioning, nothing even happened to my given hotbar, as if the addon did absolutely nothing. Even after a relog, nothing changed.

You should really either add all the different UI elements by default and have them all disabled by default so we don't have to find the element names ourselves; or provide a straight up list in some documentation of all the UI elements the plugin can interact with instead of having to find them through xldata. People who never had to use `/xldata` won't know a thing about where to find the different elements.

**Comment by Drahsid** [comment]
Directly in the readme, you can read the following:
> You can add units by using `/prhudadd [unit name]`. To find the name of a unit, you can look at the addon inspector using `/xldata`

When opening `/xldata`, you can see that it starts on the `Server OpCode` data kind. Clicking on the dropdown will show a list of other kinds. Near the bottom is the Addon Inspector. A quick glance through the units list will reveal that the action bars are called `_ActionBar` and `_ActionBar01` -> `_ActionBar09`.

There is a ludicrously numerous number of total UI units, so preemptively adding every possible UI unit may both be redundant, and horrifyingly insane for the end user. This would be no better than asking the end user to look at the addon inspector with 2 button clicks, so that they can see a smaller, more relevant list.

In the future, I am going to add a better editor, and with that, an easier way to find the units you want.

**Comment by Drahsid** [comment]
I have added an addon inspector, which lets users visually add and edit UI elements. This indirectly solves the documentation issue outlined here, so I am closing this issue. Thanks for your patience.
